global_costmap:
  #代价地图的世界坐标系
  global_frame: map
  #机器人底座的局部坐标系
  robot_base_frame: base_link
  #代价地图的更新频率
  # update_frequency: 2.0
  update_frequency: 5.0
  #代价地图的发布频率
  publish_frequency: 5.0 # 1.0
  # footprint: [[0.177, 0.13], [-0.177, 0.13], [-0.177, -0.13], [0.177, -0.13]]
  robot_radius: 0.01
  
  #决定代价地图是否需要根据map_server提供的地图信息进行初始化，如果不需要使用已有的地图或者map_server，最好将该参数设置为false
  static_map: true
  width: 6
  height: 6
  # plugins:
  #       - {name: static_layer, type: "costmap_2d::StaticLayer"}
  #       - {name: obstacle_layer,  type: "costmap_2d::ObstacleLayer"}
  #       - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
  cost_scaling_factor: 30
  inflation_radius: 0.16
