local_costmap:
  #代价地图的世界坐标系
  global_frame: map
  #机器人底座的局部坐标系
  robot_base_frame: base_link
  #代价地图的更新频率
  update_frequency: 8.0
  #代价地图的发布频率
  publish_frequency: 8.0

  #决定代价地图是否需要根据map_server提供的地图信息进行初始化，如果不需要使用已有的地图或者map_server，最好将该参数设置为false
  static_map: false
  #是否使用动态窗口，默认为false，在静态的全局地图中，地图不会变化
  rolling_window: true
  #代价地图宽度
  # width: 2
  width: 3
  #代价地图高度
  # height: 2
  height: 3

  # plugins:
  #       - {name: obstacle_layer,  type: "costmap_2d::ObstacleLayer"}
  #       - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
  cost_scaling_factor: 25
  inflation_radius: 0.2

  # footprint: [[0.175, 0], [-0.175, 0], [-0.175, 0], [0.175, 0]]
  # footprint: [[0.177, 0.13], [-0.177, 0.13], [-0.177, -0.13], [0.177, -0.13]]
  robot_radius: 0.01
  # 此外形应与TEB中的外形一致，或者至少在大小上没有太大的差别

 